### ISSUE TITLE
Non English locale incompatibility

### ISSUE THREAD

**Issue by kingio** [sindresorhus/tasklist#11]
¡TY for making this wrapper!

**O.S**: Windows 10
**Node:** v6.11.1
**tasklist**: v.3.1.0

If i run:
```js
tasklist({
    filter: [
        "Imagename eq chromeASDFG.exe"
    ]
}).then(tasks => {
    if (tasks.length > 0) {
        return;
    }

  // i do my things..
});
```

I get the following error:
`(node:9220) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'replace' of undefined`

While doing:
```js
tasklist({
    filter: [
        "Imagename eq chrome.exe"
    ]
}).then(tasks => {
    if (tasks.length > 0) {
        return;
    }

  // i do my things..
});
```

Works fine

**Comment by MarkTiedemann** [comment]
This should have been fixed with the latest release `v.3.1.0`. Can you please check which version of this module you have installed?

And in case you have the newest version, could you please run `tasklist /fi "imagename eq does-not-exist.exe"` and post the output here?

**Comment by kingio** [comment]
Got the latest version, probably it's a locale thing, output is:
`INFORMACIÓN: no hay tareas ejecutándose que coincidan con los
criterios especificados.`

https://github.com/sindresorhus/tasklist/blob/master/index.js#L49

**Comment by kingio** [comment]
Maybe a non language dependent hack would be to look for:
1.  `===` => if present there are results
2. If  `===` it's not present, look for `/?` => Wrong command/argument set (cmd returns the typical read the manual message including `TASKLIST /?` command)
3. If `/?` it's not present => no results

**Comment by MarkTiedemann** [comment]
I guess a quick fix would be to change L49 to `.startsWith('INFO')` I guess. :smile:

Another one would be to check in the mapping, for example, if `pid` is `undefined`, and if it is, just return `[]`.

EDIT: Posted at the same time. Good ideas, @kingio! But I'm not quite sure they're gonna work:

- The `===` would not work since we're using the `/fo csv` option, and there is no such string present in the csv formatting.
- `/?` could be included in the window title of a task when we run it in `/v` verbose mode so that might also fail.

**Comment by kingio** [comment]
mmm, maybe this?:
1. `,"PID",` 
2. `"TASKLIST /?"`

**Comment by MarkTiedemann** [comment]
Yeah. With CSV formatting the headers always start with `"Image Name","PID", ...` so that would work -- except we're using the `/nh` "no headers" option at the moment. But I guess we can get rid of that and just let the CSV parser remove the headers.

And yeah, searching for `"TASKLIST /?"` for identifying incorrect parameters sounds good to me, too.

Thanks for the suggestions! :)

**Comment by kingio** [comment]
@MarkTiedemann warning! only PID is common for all languages, "Image name" is `"Nombre de imagen"` for me:
`"Nombre de imagen","PID","Nombre de sesión","Núm. de sesión","Uso de memoria"`

**Comment by MarkTiedemann** [comment]
Oh, that's why! Did not know that -- thanks again! :)

**Comment by Zamiell** [comment]
Any word on fixing this? Still getting it on Russian installations 2 months later.

**Comment by sindresorhus** [comment]
PR welcome if anyone wants to see this fixed :)
