### ISSUE TITLE
Even no result when using tasklist through ps-list and electron on Windows 10?

### ISSUE THREAD

**Issue by pamoller** [sindresorhus/tasklist#12]
```> npm install tasklist --save
> npm
> require('tasklist')()
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }```

**Comment by MarkTiedemann** [comment]
Hi @pamoller,

I think you forgot to await the result of the returned [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

Instead of `require('tasklist')()`, try:

```js
require('tasklist')()
  .then(tasks => console.log(tasks))
  .catch(err => console.error(err))
```

Or, if you can use [`async`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) / [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await), try:

```js
try {
  const tasks = await require('tasklist')()
  console.log(tasks)
} catch (err) {
  console.error(err)
}
```

Hope that helps.

**Comment by pamoller** [comment]
Ok, thanks a lot. Running tasklist().then(...) periodically by setInterval or setTimeout, like I did before, collects a increasing number of entries in the process list. Any idea to avoid the entries? ps-list works well under lnx :).
