### ISSUE TITLE
Poor performance on Windows 10

### ISSUE THREAD

**Issue by mceachen** [sindresorhus/tasklist#16]
Moved issue from [ps-list](https://github.com/sindresorhus/ps-list/issues/18):

```
$ time node -e 'require("tasklist")().then(arr => console.log("found " + arr.length + " procs"))'
found 222 procs

real    0m4.688s
user    0m0.000s
sys     0m0.015s
```

Note that `tasklist` on this machine takes ~1/5 of a second:

```
$ time tasklist | wc -l
225

real    0m0.262s
user    0m0.000s
sys     0m0.062s
```

System information:
* Windows 10 Pro Version 10.0.17134 Build 17134
* node v8.11.3

**Comment by mceachen** [comment]
The [times from appveyor](https://ci.appveyor.com/project/sindresorhus/tasklist) look fine, so I wonder what's different with my environment. I'll close this until I can repro on Appveyor.

**Comment by mceachen** [comment]
Ah, so running `tasklist` with the options that this module uses, `tasklist /v /nh /fo csv`, makes (at least my) windows' tasklist render extremely slowly.

If I remove the `/v` rendering is back to under a second.

**Comment by MarkTiedemann** [comment]
This is a bug indeed.

As documented in the Readme, `verbose` should  be `false` by default since it "may have a considerable performance impact".

Unfortunately, the `verbose` option is not considered when determining the arguments that `tasklist` is being executed with. Instead, the `/v` (verbose) flag is always passed along.

Thank you for opening this issue, @mceachen. And thank you for the PR to fix it right away!
