### ISSUE TITLE
Error when filtering returns no results

### ISSUE THREAD

**Issue by baileyherbert** [sindresorhus/tasklist#9]
If you specify a filter, like this:

```
tasklist({
  filter: ["Imagename eq httpd.exe"]
})
```

When no matches are found, the promise is rejected with an error:

```
TypeError: Cannot read property 'replace' of undefined
    at data.map.task (D:\wamp\node_modules\tasklist\index.js:53:40)
    at Array.map (native)
    at pify.then.then.data (D:\wamp\node_modules\tasklist\index.js:
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Expected result is the promise being resolved with an empty array.

**Comment by MarkTiedemann** [comment]
This is a bug indeed.

When no tasks are found, `tasklist` prints `INFO: No tasks are running which match the specified criteria.` (or something similar based on the user's language).

`neat-csv` converts this into:

```
[ Row {
    imageName: 'INFO: No tasks are running which match the specified criteria.',
    pid: undefined,
    sessionName: undefined,
    sessionNumber: undefined,
    memUsage: undefined } ]
```

And the function to normalize the tasks fails in line 55:
```js
task.memUsage = Number(task.memUsage.replace(/[^\d]/g, '')) * 1024;
```

---------------------

To fix this, we could either check the printed output for the `INFO` key (since this is not language dependent AFAIK), or handle normalizing errors gracefully with a try-catch block, or both. :)
